/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.4/samples
 */
group = "org.eventonight.eventonight"
version = "1.0-SNAPSHOT"

allprojects {
    repositories {
        mavenCentral()
    }
}