/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.4/userguide/building_swift_projects.html in the Gradle documentation.
 */

rootProject.name = "EvenToNight"

plugins {
    id("org.danilopianini.gradle-pre-commit-git-hooks") version "2.1.2"
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

gitHooks{
    preCommit { tasks("formatAndLintPreCommit", "updateAndCheckEnvSetup") }
    commitMsg { conventionalCommits() }
    createHooks(true)
}

// Refresh the local .env from .env.template on every configuration (e.g. IDE sync),
// the same moment the git hooks above get (re)installed. Uses providers.exec so it
// stays configuration-cache compatible. Best-effort: a failure here must never break
// the project import — the pre-commit hook still validates the .env on commit.
val isWindows = System.getProperty("os.name").lowercase().contains("windows")
val updateEnvOutput = providers.exec {
    workingDir = rootDir
    isIgnoreExitValue = true
    if (isWindows) {
        commandLine("powershell", "-Command", "& 'C:\\Program Files\\Git\\bin\\bash.exe' -c './scripts/updateLocalEnv.sh'")
    } else {
        commandLine("bash", "scripts/updateLocalEnv.sh")
    }
}
runCatching {
    print(updateEnvOutput.standardOutput.asText.get())
    val exitCode = updateEnvOutput.result.get().exitValue
    if (exitCode != 0) println("⚠️  updateEnvFile exited with code $exitCode")
}.onFailure { println("⚠️  Could not update .env automatically: ${it.message}") }

include("libs:ts-common")
include("libs:nestjs-common")

include("services:users")
include("services:events")
include("services:frontend")
include("services:media")
include("services:interactions")
include("services:chat")
include("services:ticketing")
include("services:notifications")
