/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.4/userguide/building_swift_projects.html in the Gradle documentation.
 */

rootProject.name = "EvenToNight"

plugins {
    id("org.danilopianini.gradle-pre-commit-git-hooks") version "2.1.2"
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

gitHooks{
    preCommit { tasks("formatAndLintPreCommit", "updateAndCheckEnvSetup") }
    commitMsg { conventionalCommits() }
    createHooks(true)
}

include("services:users")
include("services:events")
include("services:frontend")
include("services:media")
include("services:interactions")
include("services:chat")
