services:
  notifications:
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notifications.rule=Host(`notifications.${HOST}`)"
      - "traefik.http.routers.notifications.entrypoints=web"
      - "traefik.http.services.notifications.loadbalancer.server.port=${NOTIFICATIONS_SERVICE_PORT}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_eventonight-network"
      - "traefik.http.routers.notifications.middlewares=global-retry@file,global-cb@file"    
    depends_on:
      mongo-notifications:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      users:
        condition: service_healthy

  mongo-notifications:
    restart: unless-stopped

networks:
  eventonight-network:
    driver: bridge
  notifications-network:
    driver: bridge
