openapi: 3.0.1
info:
  title: EvenToNight - Chat API
  version: 1.0.0
paths:
  /users/{userId}/conversations:
    post:
      summary: Send first message and create a new conversation with an organization
      servers:
        - url: http://localhost:9040
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            example: "user123"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateConversationMessageDto'
      responses:
        '201':
          description: Message sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponseDto'
        '400':
          description: Bad Request
        '404':
          description: Organization or Member not found
    get:
      summary: Get conversations for a user
      servers:
        - url: http://localhost:9040
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            example: "user123"
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of conversations
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "conv123"
                        organizationId:
                          type: string
                          example: "org456"
                        organizationName:
                          type: string
                          example: "EventoNight"
                        organizationAvatar:
                          type: string
                          example: "https://example.com/avatar.png"
                        memberId:
                          type: string
                          example: "member321"
                        memberName:
                          type: string
                          example: "John Doe"
                        memberAvatar:
                          type: string
                          example: "https://example.com/member_avatar.png"
                        lastMessage:
                          type: object
                          properties:
                            content:
                              type: string
                              example: "Hello, can I get more information about your events?"
                            senderId:
                              type: string
                              example: "user123"
                            timestamp:
                              type: string
                              format: date-time
                        unreadCount:
                          type: integer
                          example: 5
                  limit:
                    type: integer
                    example: 20
                  offset:
                    type: integer
                    example: 0
                  hasMore:
                    type: boolean
                    example: false
        '400':
          description: Bad Request
        '404':
          description: User not found
  
  /users/{userId}/conversations/{conversationId}:
    post:
      summary: Send a message in an existing conversation for a user
      servers:
        - url: http://localhost:9040
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            example: "user123"
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
            example: "conv123"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageDto'
      responses:
        '201':
          description: Message sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponseDto'
        '400':
          description: Bad Request
        '404':
          description: Conversation not found
    
    get:
      summary: Get specific conversation of a user by ID
      servers:
        - url: http://localhost:9040
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            example: "user123"
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
            example: "conv123"
      responses:
        '200':
          description: Conversation details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "conv123"
                  organizationId:
                    type: string
                    example: "org456"
                  memberId:
                    type: string
                    example: "member321"
                  "createdAt":
                    type: string
                    format: date-time
                  "updatedAt":
                    type: string
                    format: date-time
        '400':
          description: Bad Request
        '404':
          description: Conversation not found

  /users/{userId}/unread/count:
    get:
      summary: Get total unread message count for a user
      servers:
        - url: http://localhost:9040
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            example: "user123"
      responses:
        '200':
          description: Total unread message count
          content:
            application/json:
              schema:
                type: object
                properties:
                  unreadCount:
                    type: integer
                    example: 15
        '400':
          description: Bad Request
        '404':
          description: User not found    
  
  /users/{userId}/conversations/{conversationId}/messages:
    get:
      summary: Get messages in a conversation for a user
      servers:
        - url: http://localhost:9040
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            example: "user123"
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
            example: "conv123"
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of messages in the conversation
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: The unique identifier of the message
                          example: "msg789"
                        conversationId:
                          type: string
                          description: The ID of the conversation
                          example: "conv123"
                        sender:
                          type: object
                          properties:
                            id:
                              type: string
                              description: The ID of the sender
                              example: "user123"
                            name:
                              type: string
                              description: The name of the sender
                              example: "John Doe"
                            avatar:
                              type: string
                              description: The avatar URL of the sender
                              example: "https://example.com/avatar.png"
                        content:
                          type: string
                          example: "Hello, can I get more information about your events?"
                        createdAt:
                          type: string
                          format: date-time
                          description: The time when the message was sent
                        isRead:
                          type: boolean
                          description: Whether the message has been read
                  limit:
                    type: integer
                    example: 20
                  offset:
                    type: integer
                    example: 0
                  hasMore:
                    type: boolean
                    example: false
        '400':
          description: Bad Request
        '404':
          description: Conversation not found

  /users/{userId}/conversations/{conversationId}/read:
    patch:
      summary: Mark messages in a conversation as read for a user
      servers:
        - url: http://localhost:9040
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
            example: "conv123"
        - name: userId
          in: path
          required: true
          schema:
            type: string
            description: The ID of the user marking messages as read
            example: "user123"
      responses:
        '204':
          description: Messages marked as read successfully
        '400':
          description: Bad Request
        '404':
          description: Conversation not found
  
components:
  schemas:
    CreateConversationMessageDto:
      type: object
      properties:
        recipientId:
          type: string
          description: The ID of the organization to start a conversation with
          example: "org456"
        content:
          type: string
          description: The content of the initial message
          example: "Hello, can I get more information about your events?"
      required:
        - recipientId
        - content

    SendMessageDto:
      type: object
      properties:
        content:
          type: string
          description: The content of the message
          example: "Hello, can I get more information about your events?"
      required:
        - content

    MessageResponseDto:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of the message
          example: "msg789"
        conversationId:
          type: string
          description: The ID of the conversation
          example: "conv123"
        senderId:
          type: string
          description: The ID of the sender
          example: "user123"
        content:
          type: string
          description: The content of the message
          example: "Hello, can I get more information about your events?"
        createdAt:
          type: string
          format: date-time
          description: The time when the message was sent
      required:
        - id
        - conversationId
        - senderId
        - content
        - timestamp
    