openapi: 3.0.1
info:
  title: EvenToNight - Events API
  version: 1.0.0
paths:
  /:
    post:
      summary: Create a new event draft
      description: Creates a new event in draft status with the provided information.
      servers:
        - url: http://localhost:9010
          description: Events service (local development)
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - title
                - description
                - poster
                - tags
                - location
                - date
                - price
                - id_creator
              properties:
                title:
                  type: string
                  description: Event title
                  example: "Summer Music Festival"
                description:
                  type: string
                  description: Event description
                  example: "An amazing summer music festival with top artists"
                poster:
                  type: string
                  format: binary
                  description: Event poster image file
                tags:
                  type: string
                  description: Comma-separated list of event tags
                  example: "Concert,Festival,Live Music"
                location:
                  type: string
                  description: Event location
                  example: "Central Park, New York"
                date:
                  type: string
                  format: date-time
                  description: Event date and time
                  example: "2025-07-15T20:00:00"
                price:
                  type: number
                  format: double
                  description: Event ticket price
                  example: 25.50
                id_creator:
                  type: string
                  description: ID of the event creator
                  example: "user-123"
                id_collaborator:
                  type: string
                  description: Optional ID of a collaborator
                  required: false
                  example: "user-456"
      responses:
        '201':
          description: Event draft created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_event:
                    type: string
                    description: Unique identifier of the created event
                    example: "evt_789xyz"
        '207':
          description: Partial success - event created but poster upload failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_event:
                    type: string
                    description: Unique identifier of the created event
                    example: "evt_789xyz"
                  warning:
                    type: string
                    description: Warning message about the poster upload failure
                    example: "Event created but poster upload failed"
        '400':
          description: Bad request - validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message describing what went wrong
                    example: "Invalid date format"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Unknown error occurred during event creation"
      tags:
        - Event Command API
    
    get:
      summary: Get all public events
      description: Retrieves a list of all events published.
      servers:
        - url: http://localhost:9010
          description: Events service (local development)
        - url: https://events.eventonight.site
          description: Events service (production)
      responses:
        '200':
          description: A JSON array of events
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id_event:
                      type: string
                      description: Event ID
                    title:
                      type: string
                      description: Event title
                    description:
                      type: string
                      description: Event description
                    poster:
                      type: string
                      description: Event poster filename
                    tag:
                      type: array
                      items:
                        type: string
                      description: List of event tags
                    location:
                      type: string
                      description: Event location
                    date:
                      type: string
                      format: date-time
                      description: Event date and time
                    price:
                      type: number
                      format: double
                      description: Event ticket price  
                    status:
                      type: string
                      enum: [PUBLISHED]
                      description: Event status
                    instant:
                      type: string
                      format: date-time
                      description: Event creation timestamp
                    id_creator:
                      type: string
                      description: ID of the event creator
                    id_collaborator:
                      type: string
                      description: ID of the collaborator (if any)
                      nullable: true
        '404':
          description: No events found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Could not retrieve events"
          
      tags:
        - Event Query API
  
  /{poster/:id_event}:
    post:
      summary: Update event poster
      description: Updates the poster image for a specific event.
      servers:
        - url: http://localhost:9010
          description: Events service (local development)
      parameters:
        - in: path
          name: id_event
          required: true
          schema:
            type: string
          description: The ID of the event to update the poster for.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                poster:
                  type: string
                  format: binary
                  description: New event poster image file
      responses:
        '200':
          description: Event poster updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                    example: "Event poster updated successfully"
        '400':
          description: Bad request - validation error

  /{id_event}:
    get:
      summary: Get event details by ID
      description: Retrieves detailed information about a specific event.
      servers:
        - url: http://localhost:9010
          description: Events service (local development)
        - url: https://events.eventonight.site
          description: Events service (production)
      parameters:
        - name: id_event
          in: path
          required: true
          description: The ID of the event to retrieve
          schema:
            type: string
            example: "event-uuid-123"
      responses:
        '200':
          description: Event details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_event:
                    type: string
                    description: Event ID
                  title:
                    type: string
                    description: Event title
                  description:
                    type: string
                    description: Event description
                  poster:
                    type: string
                    description: Event poster filename
                  tag:
                    type: array
                    items:
                      type: string
                    description: List of event tags
                  location:
                    type: string
                    description: Event location
                  date:
                    type: string
                    format: date-time
                    description: Event date and time
                  price:
                    type: number
                    format: double
                    description: Event ticket price
                  status:
                    type: string
                    enum: [DRAFT, PUBLISHED, CANCELLED]
                    description: Event status
                  instant:
                    type: string
                    format: date-time
                    description: Event creation timestamp
                  id_creator:
                    type: string
                    description: ID of the event creator
                  id_collaborator:
                    type: string
                    description: ID of the collaborator (if any)
                    nullable: true
              example:
                id_event: "event-uuid-123"
                title: "Summer Music Festival"
                description: "An amazing summer music festival"
                poster: "poster-123.jpg"
                tag: ["Concert", "Festival", "Live Music"]
                location: "Central Park, New York"
                date: "2025-07-15T20:00:00"
                status: "DRAFT"
                instant: "2025-11-22T10:00:00Z"
                id_creator: "user-123"
                id_collaborator: ""
        '404':
          description: Event not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Event not found"  
      tags:
        - Event Query API 
  
  /tags:
    get:
      summary: Get available event tags grouped by category
      description: Returns a list of tag categories and their tags used by the Events service.
      servers:
        - url: http://localhost:9010
          description: Events service (local development)
        - url: https://events.eventonight.site
          description: Events service (production)
      responses:
        '200':
          description: A JSON array of tag categories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    category:
                      type: string
                      description: Tag category name
                    tags:
                      type: array
                      items:
                        type: string
                      description: List of tags for the category
              example: |
                [
                  {"category": "TypeOfEvent", "tags": ["Party", "Live Music"]},
                  {"category": "VenueType", "tags": ["Club", "Bar"]}
                ]
      tags: 
        - Event Tag Routes   
  
  /tags/{category}:
    get:
      summary: Get tags by category
      description: Returns the list of tags associated with the specified category.
      servers:
        - url: http://localhost:9010
          description: Events service (local development)
        - url: https://events.eventonight.site
          description: Events service (production)
      parameters:
        - in: path
          name: category
          required: true
          schema:
            type: string
            enum:
              - TypeOfEvent
              - VenueType
              - MusicGenre
              - Theme
              - Target
              - Extra
          description: The category of tags to retrieve.
      responses:
        '200':
          description: List of tags for the given category.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      tags:
        - Event Tag Routes