services:
  events:
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.events.rule=Host(`events.${HOST}`)"
      - "traefik.http.routers.events.entrypoints=web"
      - "traefik.http.services.events.loadbalancer.server.port=${EVENTS_SERVICE_PORT}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_eventonight-network"
      - "traefik.http.routers.events.middlewares=global-retry@file,global-cb@file"    
    depends_on:
      mongo-events:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      users:
        condition: service_healthy

  mongo-events:
    volumes:
      - ./scripts/init-mongo-replica-set.sh:/scripts/init-mongo-replica-set.sh:ro
    restart: unless-stopped

networks:
  eventonight-network:
    driver: bridge
  events-network:
    driver: bridge
