services:
  events:
    deploy:
      replicas: ${EVENTS_SERVICE_REPLICAS:-1}
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.events.rule=Host(`events.${HOST}`)"
        - "traefik.http.routers.events.entrypoints=web"
        - "traefik.http.services.events.loadbalancer.server.port=${EVENTS_SERVICE_PORT}"
        - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_eventonight-network"
        - "traefik.http.routers.events.middlewares=global-retry@file,global-cb@file"

  mongo-events:
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.id.1 == true
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

networks:
  eventonight-network:
    driver: overlay
    attachable: true
  events-network:
    driver: overlay
