services:
  seed:
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  eventonight-network:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_eventonight-network
