services:
  keycloak:
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.${HOST}`)"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"
      - "traefik.http.routers.auth.middlewares=global-retry@file,global-cb@file"    
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      postgres-keycloak:
        condition: service_healthy

  keycloak-provision:
    depends_on:
      keycloak:
        condition: service_healthy

networks:
  eventonight-network:
    driver: bridge
  keycloak-network:
    driver: bridge
