services:
  postgres-keycloak:
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.postgres.keycloak.1 == true
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  keycloak:
    depends_on: []
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.auth.rule=Host(`auth.${HOST}`)"
        - "traefik.http.routers.auth.entrypoints=web"
        - "traefik.http.services.auth.loadbalancer.server.port=8080"
  keycloak-provision:
    depends_on: []
    deploy:
      mode: replicated-job

networks:
  eventonight-network:
    driver: overlay
    attachable: true
  keycloak-network:
    driver: overlay
