services:
  error-pages:
    restart: unless-stopped

  traefik:
    restart: unless-stopped
    volumes:
      - ./infrastructure/gateway/config/config.yaml:/etc/traefik/traefik.yaml:ro

networks:
  eventonight-network:
    driver: bridge
