services:
  ticketing:
    deploy:
      replicas: ${TICKETING_SERVICE_REPLICAS:-1}
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ticketing.rule=Host(`ticketing.${HOST}`) && !PathPrefix(`/internal`)"
        - "traefik.http.routers.ticketing.entrypoints=web"
        - "traefik.http.services.ticketing.loadbalancer.server.port=${TICKETING_SERVICE_PORT}"
        - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_eventonight-network"
    depends_on: []
  mongo-ticketing:
    depends_on: []
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.ticketing.1 == true
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  mongo-ticketing-2:
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.ticketing.2 == true
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  mongo-ticketing-3:
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.ticketing.3 == true
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

networks:
  eventonight-network:
    driver: overlay
    attachable: true
  ticketing-network:
    driver: overlay
