services:
  ticketing:
    restart: unless-stopped
    environment:
      - REPLICA_SET_NODES_NUMBER=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ticketing.rule=Host(`ticketing.${HOST}`) && !PathPrefix(`/internal`)"
      - "traefik.http.routers.ticketing.entrypoints=web"
      - "traefik.http.services.ticketing.loadbalancer.server.port=${TICKETING_SERVICE_PORT}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_eventonight-network"
      - "traefik.http.routers.ticketing.middlewares=global-retry@file,global-cb@file"    
    depends_on:
      mongo-ticketing:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      users:
        condition: service_healthy

  mongo-ticketing:
    environment:
        - REPLICA_SET_NODES_NUMBER=1
    restart: unless-stopped

networks:
  eventonight-network:
    driver: bridge
  ticketing-network:
    driver: bridge
