object DockerCommands {
    const val TEARDOWN_TEST_ENVIRONMENT = "./scripts/composeDevEnvironment.sh --project-name eventonight-test-environment down -v --remove-orphans"
    const val TEARDOWN_DEV_ENVIRONMENT = "./scripts/composeDevEnvironment.sh --dev down -v --remove-orphans"
    const val TEARDOWN_APPLICATION_ENVIRONMENT = "./scripts/composeApplication.sh down --dev -v --remove-orphans"
    const val TEARDOWN_KEYCLOAK = "./scripts/composeAll.sh -p ./infrastructure/authentication/ --dev down -v --remove-orphans --project-name keycloak-stack"
    const val TEARDOWN_FRONTEND_ENVIRONMENT = "$TEARDOWN_APPLICATION_ENVIRONMENT -eP services/frontend --project-name eventonight-frontend-environment"
    const val TEARDOWN_MEDIA = "./scripts/composeAll.sh -p ./services/media/ --dev down -v --remove-orphans --project-name media-service"
    const val TEARDOWN_PAYMENTS_ENVIRONMENT = "$TEARDOWN_APPLICATION_ENVIRONMENT -eP services/payments --project-name eventonight-payments-environment"
    const val SETUP_TEST_ENVIRONMENT = "./scripts/composeDevEnvironment.sh --project-name eventonight-test-environment up -d --force-recreate --wait"
    const val SETUP_DEV_ENVIRONMENT = "./scripts/composeDevEnvironment.sh --dev up -d --force-recreate --wait"
    const val SETUP_APPLICATION_ENVIRONMENT = "./scripts/composeApplication.sh --dev --init-db up -d --build --force-recreate --wait"
    const val SETUP_KEYCLOAK = "./scripts/composeAll.sh -p ./infrastructure/authentication/ --dev up --force-recreate --build -d --wait --project-name keycloak-stack && docker wait keycloak-stack-keycloak-provision-1"
    const val SETUP_FRONTEND_ENVIRONMENT = "$SETUP_APPLICATION_ENVIRONMENT -eP services/frontend --project-name eventonight-frontend-environment"
    const val SETUP_MEDIA_SERVICE = "./scripts/composeAll.sh -p ./services/media/ --dev up --force-recreate --build -d --wait --project-name media-service"
    const val SETUP_PAYMENTS_ENVIRONMENT = "$SETUP_APPLICATION_ENVIRONMENT -eP services/payments --project-name eventonight-payments-environment"
}