services:
  chat:
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat.rule=Host(`chat.${HOST}`)"
      - "traefik.http.routers.chat.entrypoints=web"
      - "traefik.http.services.chat.loadbalancer.server.port=${CHAT_SERVICE_PORT}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_eventonight-network"
      - "traefik.http.routers.chat.middlewares=global-retry@file,global-cb@file,global-rate-limit@file"    
    depends_on:
      mongo-chat:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      users:
        condition: service_healthy

  mongo-chat:
    volumes:
      - ./scripts/init-mongo-replica-set.sh:/scripts/init-mongo-replica-set.sh:ro
    restart: unless-stopped

networks:
  eventonight-network:
    driver: bridge
  chat-network:
    driver: bridge
