services:
  interactions:
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.interactions.rule=Host(`interactions.${HOST}`)"
      - "traefik.http.routers.interactions.entrypoints=web"
      - "traefik.http.services.interactions.loadbalancer.server.port=${INTERACTIONS_SERVICE_PORT}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_eventonight-network"
      - "traefik.http.routers.interactions.middlewares=global-errors@file,global-retry@file,global-cb@file,global-rate-limit@file"    
    depends_on:
      mongo-interactions:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      users:
        condition: service_healthy

  mongo-interactions:
    volumes:
      - ./scripts/init-mongo-replica-set.sh:/scripts/init-mongo-replica-set.sh:ro
    restart: unless-stopped

networks:
  eventonight-network:
    driver: bridge
  interactions-network:
    driver: bridge
