services:
  media:
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media.rule=Host(`media.${HOST}`)"
      - "traefik.http.routers.media.entrypoints=web"
      - "traefik.http.services.media.loadbalancer.server.port=9020"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_eventonight-network"
      - "traefik.http.routers.media.middlewares=global-errors@file,global-retry@file,global-cb@file,global-rate-limit@file"    
    depends_on:
      - minio

  minio:
    restart: unless-stopped
    ports:
      - "9021:9000"

networks:
  eventonight-network:
    driver: bridge
  media-network:
    driver: bridge
