services:
  rabbitmq:
    ports:
      - '15672:15672'

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    networks:
      - dev-network
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongo'
    depends_on:
      mongo:
        condition: service_healthy

networks:
  dev-network:
    driver: bridge