services:
  users:
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users.rule=Host(`users.${HOST}`)"
      - "traefik.http.routers.users.entrypoints=web"
      - "traefik.http.services.users.loadbalancer.server.port=${USERS_SERVICE_PORT}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_eventonight-network"
      - "traefik.http.routers.users.middlewares=global-retry@file,global-cb@file"    
    depends_on:
      mongo-users:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      keycloak-provision:
        condition: service_completed_successfully

  mongo-users:
    restart: unless-stopped

networks:
  eventonight-network:
    driver: bridge
  users-network:
    driver: bridge
