services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      - eventonight-network
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-admin}

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'status']
      interval: 5s
      timeout: 200s
      retries: 100
      start_period: 200s

volumes:
  rabbitmq-data:

networks:
  eventonight-network:
