services:
  rabbitmq:
    hostname: "rabbitmq-{{.Task.Slot}}"
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
    configs:
      - source: rabbitmq_conf
        target: /etc/rabbitmq/rabbitmq.conf
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

configs:
  rabbitmq_conf:
    file: ./rabbitmq.conf

networks:
  eventonight-network:
    driver: overlay
    attachable: true
