# Clustering via Swarm internal DNS
cluster_formation.peer_discovery_backend = rabbit_peer_discovery_dns
cluster_formation.dns.hostname = tasks.rabbitmq
cluster_formation.node_cleanup.only_log_warning = true
cluster_formation.node_cleanup.interval = 30

# Split-brain: autoheal picks the partition with more nodes
cluster_partition_handling = autoheal
