name: Check Style
on: 
  pull_request:
    branches:
      - main

jobs:
  check-style:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Check style
        run: ./gradlew checkStyle


